In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df =  pd.read_csv("/content/G2_final_data_With_floor_and_lobby.csv")

In [ ]:
df.head()

,Location,SSID,AP01,AP02,AP03,AP04,AP05,AP06,AP07,AP08,...,AP46,AP47,AP48,AP49,AP50,AP51,AP52,AP53,AP54,Label
0,LAB_0_12PM_A_1,DAIICT_Student,-100.0,-100.0,-100.0,-100.0,-100.0,-100.0,-52.0,-68.0,...,-100,-100,-100,-100,-100,-100,-100,-100,-100,0.0
1,LAB_0_12PM_A_1,DA_Public,-52.0,-68.0,-79.2,-100.0,-83.0,-100.0,-100.0,-100.0,...,-100,-100,-100,-100,-100,-100,-100,-100,-100,0.0
2,LAB_0_12PM_A_10,DAIICT_Student,-100.0,-100.0,-100.0,-100.0,-100.0,-100.0,-75.0,-100.0,...,-100,-100,-100,-100,-100,-100,-100,-100,-100,0.0
3,LAB_0_12PM_A_10,DA_Public,-100.0,-100.0,-85.0,-100.0,-100.0,-85.0,-100.0,-100.0,...,-100,-100,-100,-100,-100,-100,-100,-100,-100,0.0
4,LAB_0_12PM_A_11,DAIICT_Student,-100.0,-100.0,-100.0,-100.0,-100.0,-100.0,-100.0,-100.0,...,-100,-100,-100,-100,-100,-100,-100,-100,-100,0.0

In [ ]:
df['Label'] = df['Label'].astype('Int64')

In [ ]:
df['Label'].value_counts()

Label
3     208
9     208
10    208
5     208
11    208
4     204
0     192
6     192
1     192
8     192
2     168
7     144
Name: count, dtype: Int64

In [ ]:
df= df.dropna()

In [ ]:
X= df.iloc[:, 2:-1]

In [ ]:
X

,AP01,AP02,AP03,AP04,AP05,AP06,AP07,AP08,AP09,AP10,...,AP45,AP46,AP47,AP48,AP49,AP50,AP51,AP52,AP53,AP54
0,-100.0,-100.0,-100.000000,-100.0,-100.000000,-100.0,-52.0,-68.0,-79.2,-100.0,...,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100
1,-52.0,-68.0,-79.200000,-100.0,-83.000000,-100.0,-100.0,-100.0,-100.0,-100.0,...,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100
2,-100.0,-100.0,-100.000000,-100.0,-100.000000,-100.0,-75.0,-100.0,-100.0,-100.0,...,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100
3,-100.0,-100.0,-85.000000,-100.0,-100.000000,-85.0,-100.0,-100.0,-100.0,-100.0,...,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100
4,-100.0,-100.0,-100.000000,-100.0,-100.000000,-100.0,-100.0,-100.0,-100.0,-100.0,...,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2323,-100.0,-100.0,-84.357143,-100.0,-76.633333,-77.8,-100.0,-100.0,-100.0,-100.0,...,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100
2324,-100.0,-100.0,-100.000000,-100.0,-100.000000,-100.0,-100.0,-100.0,-100.0,-87.6,...,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100
2325,-100.0,-100.0,-100.000000,-84.0,-75.000000,-75.8,-100.0,-100.0,-100.0,-100.0,...,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100
2326,-100.0,-100.0,-100.000000,-100.0,-100.000000,-100.0,-100.0,-100.0,-100.0,-84.0,...,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100
2327,-100.0,-100.0,-100.000000,-84.0,-100.000000,-77.0,-100.0,-100.0,-100.0,-100.0,...,-100,-100,-100,-100,-100,-100,-100,-100,-100,-100

In [ ]:
y = df.iloc[:, -1]

In [ ]:
y

0       0
1       0
2       0
3       0
4       0
       ..
2323    8
2324    8
2325    8
2326    8
2327    8
Name: Label, Length: 2324, dtype: Int64

In [ ]:
y.value_counts()

Label
3     208
9     208
10    208
5     208
11    208
4     204
0     192
6     192
1     192
8     192
2     168
7     144
Name: count, dtype: Int64

In [ ]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test =  train_test_split(X , y , test_size= 0.2 , random_state= 42)

In [ ]:
y_train.isna().sum()

0

In [ ]:
import pickle
import warnings
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

# Suppress warnings
warnings.filterwarnings("ignore")

# Initialize individual classifiers
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
dt_clf = DecisionTreeClassifier(random_state=42)
knn_clf = KNeighborsClassifier(n_neighbors=3)
svm_clf = SVC(probability=True, random_state=42)

# Create a voting classifier with majority voting
voting_clf = VotingClassifier(
    estimators=[
        ('RandomForest', rf_clf),
        ('DecisionTree', dt_clf),
        ('KNN', knn_clf),
        ('SVM', svm_clf)
    ],
    voting='hard'
)

# Perform cross-validation on the voting classifier
cv_scores = cross_val_score(voting_clf, X_train, y_train, cv=5, scoring='accuracy')
print(f"VotingClassifier: {cv_scores.mean():.2f}")

# Fit the model and save it
voting_clf.fit(X_train, y_train)
with open('voting_classifier_model.pkl', 'wb') as file:
    pickle.dump(voting_clf, file)

# Evaluate individual classifiers with cross-validation
for clf_name, clf in voting_clf.named_estimators_.items():
    scores = cross_val_score(clf, X_train, y_train, cv=5, scoring='accuracy')
    print(f"{clf_name}: {scores.mean():.2f}")

# Evaluate the ensemble model on the test set
y_pred = voting_clf.predict(X_test)
test_accuracy = accuracy_score(y_test, y_pred)
print(f"VotingClassifier Test Accuracy: {test_accuracy:.2f}")

VotingClassifier: 0.82
RandomForest: 0.88
DecisionTree: 0.72
KNN: 0.71
SVM: 0.73
VotingClassifier Test Accuracy: 0.82

In [ ]:
import pickle
import warnings
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

# Suppress warnings
warnings.filterwarnings("ignore")

# Initialize the XGBoost classifier
xgb_clf = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)

# Perform cross-validation on the XGBoost classifier
cv_scores = cross_val_score(xgb_clf, X_train, y_train, cv=5, scoring='accuracy')
print(f"XGBoost Cross-Validation Accuracy: {cv_scores.mean():.2f}")

# Fit the model
xgb_clf.fit(X_train, y_train)

# Save the trained model
with open('xgboost_model.pkl', 'wb') as file:
    pickle.dump(xgb_clf, file)

# Evaluate the model on the test set
y_pred = xgb_clf.predict(X_test)
test_accuracy = accuracy_score(y_test, y_pred)
print(f"XGBoost Test Set Accuracy: {test_accuracy:.2f}")

XGBoost Cross-Validation Accuracy: 0.86
XGBoost Test Set Accuracy: 0.87

In [ ]:
import pickle
import warnings
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, cross_val_score

# Suppress warnings
warnings.filterwarnings("ignore")

# Initialize the XGBoost classifier
xgb_clf = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)

# Define the hyperparameter grid
param_grid = {
    'n_estimators': [50, 100, 150],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7],

}

# Perform GridSearchCV to find the best hyperparameters
grid_search = GridSearchCV(
    estimator=xgb_clf,
    param_grid=param_grid,
    scoring='accuracy',
    cv=5,
    verbose=1
)

# Fit the grid search to the training data
grid_search.fit(X_train, y_train)

best_xgb_clf = grid_search.best_estimator_
print(f"Best Parameters: {grid_search.best_params_}")

# Perform cross-validation with model
cv_scores = cross_val_score(best_xgb_clf, X_train, y_train, cv=5, scoring='accuracy')
print(f"XGBoost (Tuned) Cross-Validation Accuracy: {cv_scores.mean():.2f}")

best_xgb_clf.fit(X_train, y_train)

with open('xgboost_tuned_model.pkl', 'wb') as file:
    pickle.dump(best_xgb_clf, file)

y_pred = best_xgb_clf.predict(X_test)
test_accuracy = accuracy_score(y_test, y_pred)
print(f"XGBoost (Tuned) Test Set Accuracy: {test_accuracy:.2f}")

Fitting 5 folds for each of 27 candidates, totalling 135 fits
Best Parameters: {'learning_rate': 0.2, 'max_depth': 5, 'n_estimators': 150}
XGBoost (Tuned) Cross-Validation Accuracy: 0.87
XGBoost (Tuned) Test Set Accuracy: 0.87

In [ ]:
import pickle
import numpy as np

# Load the pretrained model
with open('/content/xgboost_model.pkl', 'rb') as file:
    model = pickle.load(file)

# Provided input data (make sure this is a single row with the same number of features as the training data)
X_new = np.array([[-55.53333333, -67.33333333, -77, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -72.86666667, -100, -100, -100, -100, -76, -47, -100, -100, -89, -65, -100, -100, -100, -100, -68.2, -67.86666667, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100]])  # Input should be a 2D array with the correct number of features

# Predict with the loaded model
y_pred = model.predict(X_new)

# Custom label mapping for your scenario
output_mapping = {
    0: "Floor_0_Lobby_0",
    1: "Floor_1_Lobby_1",
    2: "Floor_2_Lobby_2",
    3: "Floor_0_Lobby_3",
    4: "Floor_1_Lobby_0",
    5: "Floor_2_Lobby_1",
    6: "Floor_0_Lobby_2",
    7: "Floor_1_Lobby_3",
    8: "Floor_2_Lobby_0",
    9: "Floor_0_Lobby_1",
    10: "Floor_1_Lobby_2",
    11: "Floor_2_Lobby_3"
}

# Mapping based on specific conditions of your problem
def custom_mapping(label):
    # The value of `label` here should be the output of the model, which is mapped to these specific labels
    if label in output_mapping:
        return output_mapping[label]
    else:
        return "Unknown"

# Map the prediction to the corresponding label
predicted_label = custom_mapping(y_pred[0])

print(f"Prediction: {predicted_label}")

Prediction: Floor_0_Lobby_0

In [ ]:
import pickle
import numpy as np

# Load the pretrained model
with open('/content/xgboost_model.pkl', 'rb') as file:
    model = pickle.load(file)

# Provided input data (make sure this is a single row with the same number of features as the training data)
X_new = np.array([[-71, -87.8, -100, -100, -68, -84.2,
        -100, -100, -100, -100, -100, -100, -73, -86.4, -100, -100, -100, -100, -100,
        -100, -100, -59.4, -62.6, -100, -100, -100, -51.2, -73.8, -100, -100, -63,
        -77, -100, -100, -100, -100, -25, -33.2, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100]])  # Input should be a 2D array with the correct number of features

# Predict with the loaded model
y_pred = model.predict(X_new)

# Mapping of numeric output to string labels
output_mapping = {
    0: "Floor_0_Lobby_0",
    1: "Floor_1_Lobby_1",
    2: "Floor_2_Lobby_2",
    3: "Floor_0_Lobby_3",
    4: "Floor_1_Lobby_0",
    5: "Floor_2_Lobby_1",
    6: "Floor_0_Lobby_2",
    7: "Floor_1_Lobby_3",
    8: "Floor_2_Lobby_0",
    9: "Floor_0_Lobby_1",
    10: "Floor_1_Lobby_2",
    11: "Floor_2_Lobby_3"
}

# Map the prediction to the corresponding label
predicted_label = output_mapping.get(y_pred[0], "Unknown")  # Default to "Unknown" if no match is found

print(f"Prediction: {predicted_label}")

Prediction: Floor_1_Lobby_1